Add example use dotcms nextjs
dotCMS/next.js pull request #1
Opened 2022-04-06 19:46 UTC by oidacra

- issue 21807 implement preview mode
- issue 21806 fix detail blog page

2022-04-06 19:54 UTC, fmontes requested changes

2022-04-06 19:54 UTC, fmontes commented on examples/cms-dotcms/lib/api.js
> +            morePostsQuery: `-Blog.urlTitle:${slug}`,
We need to add `${showPreviewPosts(preview)}` here too.

2022-04-06 19:54 UTC, fmontes commented on examples/cms-dotcms/lib/api.js
> +    })
Check the indentation

2022-04-08 18:51 UTC, oidacra commented on examples/cms-dotcms/lib/api.js
> +    })
fixed

2022-04-20 12:09 UTC, rjvelazco requested changes

2022-04-20 12:09 UTC, rjvelazco commented on examples/cms-dotcms/components/dotCMS/storyblock/components/DotContent/index.js
> +export default DotContent
Since we are not gonna render any `dotContent` in this example, should we keep these files?

2022-04-20 12:09 UTC, rjvelazco commented on examples/cms-dotcms/components/link.js
> +  console.log(href)
Remove this.

2022-04-20 12:09 UTC, rjvelazco commented on examples/cms-dotcms/components/link.js
> +  console.log(title)
Remove this.

2022-04-20 20:00 UTC, merged